package com.ugo.mecash_multicurrency_wallet.enums;

public enum ResponseMessage {

    ACCOUNT_NUMBER_CANNOT_BE_FOUND("404"),WALLET_ID_MUST_BE_PROVIDED(""), INVALID_INPUT_PARAMETER("404"), SUCCESS("200"), WALLET_NOT_FOUND("404"), INTERNAL_SERVER_ERROR("500"), MAX_BALANCE_EXCEEDED("400"), MAX_TRANSACTIONS_EXCEEDED("400"),
    WALLET_IS_NOT_ACTIVE("400"), INSUFFICIENT_FUNDS("400"),
    RECIPIENT_WALLET_NOT_FOUND("404"), USER_WALLET_NOT_FOUND("404"),
    ACCESS_DENIED("403"), INVALID_PAGINATION_PARAMETERS(""),
    ERROR_FETCHING_TRANSACTION_HISTORY("-1"),
    INCORRECT_PIN("404"),
    PAGE_NUMBER_OR_PAGE_SIZE_CANNOT_BE_LESS_THAN_1("400"),
    ERROR_ACCESSING_TOKEN("400"), INCORRECT_USERNAME_OR_PASSWORD("400"),
    REGISTRATION_ERROR("400"), USERNAME_ALREADY_EXIST("400"),
    EMAIL_ALREADY_EXIST("400"), INTERNAL_SERVER_ERROR_DUE_TO_AUTHENTICATION("500"),
    BAD_REQUEST("400"), INVALID_CREDENTIALS("400"), USER_NOT_FOUND("404"), RECIPIENT_WALLET_CANNOT_BE_NULL("400");
    String statusCode;

        private ResponseMessage(String statusCode){
            this.statusCode = statusCode;
        }

        public String getStatusCode(){
            return statusCode;
        }

}
